name: "游 Arquitectura Inestable (Bug Report)"
description: "Informa sobre una anomal칤a en los protocolos cognitivos."
title: "[BUG]: "
labels: ["anomaly", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        > "Incluso el caos tiene una estructura. Ay칰dame a encontrar el error en el tejido."
  - type: textarea
    id: description
    attributes:
      label: "Naturaleza de la Anomal칤a"
      description: "쯈u칠 est치 fallando en el sistema?"
      placeholder: "Describe el comportamiento inesperado..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Pasos de Invocaci칩n (Reproducci칩n)"
      description: "쮺칩mo podemos manifestar este error?"
      placeholder: |
        1. Ejecutar protocolo...
        2. Configurar nodo...
        3. Observar el colapso.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Registros de la Bruma (Logs)"
      description: "Pega aqu칤 cualquier rastro de error o stack trace."
      render: shell
