import json
import os
from typing import Any, Dict

def generate_ts_interface(name: str, data: Dict[str, Any]) -> str:
    ts_code = f"export interface {name} {{\n"
    for key, value in data.items():
        ts_type = "any"
        if isinstance(value, str):
            ts_type = "string"
        elif isinstance(value, bool):
            ts_type = "boolean"
        elif isinstance(value, int) or isinstance(value, float):
            ts_type = "number"
        elif isinstance(value, list):
            # Simple list type inference
            if len(value) > 0 and isinstance(value[0], str):
                ts_type = "string[]"
            else:
                ts_type = "any[]"
        elif isinstance(value, dict):
            # Paradox: Recursive type generation would be better but complex for this script.
            # We'll use 'Record<string, any>' for now or nested interface if simple.
            ts_type = "Record<string, any>"
        
        # Clean key for TS
        clean_key = key.replace(" ", "_").replace("-", "_")
        ts_code += f"  {clean_key}: {ts_type};\n"
    ts_code += "}\n\n"
    return ts_code

def main():
    json_path = "../resources/ANUU_CORE_161914.json"
    output_path = "../../../Anuu_Web_Nexus/src/types/anuuTypes.ts"
    
    # Ensure output dir exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        ts_output = "// Generated by Anuu Mastery Skill (161914)\n\n"
        
        # Extract core sections
        if "ANUSET_MASTER_X4_ULTIMATE" in data:
            core = data["ANUSET_MASTER_X4_ULTIMATE"]
             # Generate types for key sections
            if "╔═══NÚCLEO_ANUU═══╗" in core:
                ts_output += generate_ts_interface("AnuuCoreIdentity", core["╔═══NÚCLEO_ANUU═══╗"])
            
            if "╔═══ESPACIO_RITUAL_89═══╗" in core:
                 if "zonas" in core["╔═══ESPACIO_RITUAL_89═══╗"]:
                    ts_output += generate_ts_interface("RitualSpaces", core["╔═══ESPACIO_RITUAL_89═══╗"]["zonas"])

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ts_output)
            
        print(f"Successfully generated TypeScript types at {output_path}")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
